# Generated by Django 2.2.4 on 2019-09-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('tipo_despesa', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
    ]
