# Generated by Django 2.2.4 on 2019-09-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mumero', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='número')),
                ('qtdQuartos', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='quantidade de quartos')),
                ('proprietario', models.CharField(max_length=30, verbose_name='proprietário')),
                ('valorComdominio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor do Comdomínio')),
            ],
        ),
    ]
