# Generated by Django 2.2.4 on 2019-09-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apartamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartamento',
            old_name='mumero',
            new_name='numero',
        ),
    ]
