# Generated by Django 2.2.4 on 2019-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190924_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30)),
                ('texto_Cliente', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('texto_Anuncio', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=30)),
                ('secao', models.CharField(max_length=50)),
                ('tipo_Anuncio', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='apartamento',
            old_name='valorComdominio',
            new_name='valorCondominio',
        ),
    ]
